# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from azure.identity import DefaultAzureCredential
from azure.iot.deviceupdate import DeviceUpdateClient
"""
# PREREQUISITES
    pip install azure-identity
    pip install azure-iot-deviceupdate
# USAGE
    python device_management_import_devices.py

    Before run the sample, please set the values of the client ID, tenant ID and client secret 
    of the AAD application as environment variables: AZURE_CLIENT_ID, AZURE_TENANT_ID,
    AZURE_CLIENT_SECRET. For more info about how to get the value, please see:
    https://docs.microsoft.com/azure/active-directory/develop/howto-create-service-principal-portal
"""
def main():
    client = DeviceUpdateClient(
        endpoint="contoso.api.adu.microsoft.com",
        instance_id="blue",
        credential=DefaultAzureCredential(),
    )

    response = client.device_management._import_devices_initial(
        import_type="All",
    )
    print(response)

# x-ms-original-file: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/d73e2aef15b4670fef9ba7b1cbce825205547212/specification/deviceupdate/data-plane/Microsoft.DeviceUpdate/preview/2021-06-01-preview/examples/DeviceManagement_ImportDevices.json
if __name__ == "__main__":
    main()
ain()
