# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
# pylint: disable=wrong-import-position

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ._patch import *  # pylint: disable=unused-wildcard-import

from ._operations import Operations  # type: ignore
from ._availability_sets_operations import AvailabilitySetsOperations  # type: ignore
from ._capacity_reservation_groups_operations import CapacityReservationGroupsOperations  # type: ignore
from ._dedicated_host_groups_operations import DedicatedHostGroupsOperations  # type: ignore
from ._images_operations import ImagesOperations  # type: ignore
from ._virtual_machine_images_edge_zone_operations import VirtualMachineImagesEdgeZoneOperations  # type: ignore
from ._virtual_machine_images_operations import VirtualMachineImagesOperations  # type: ignore
from ._log_analytics_operations import LogAnalyticsOperations  # type: ignore
from ._virtual_machine_extension_images_operations import VirtualMachineExtensionImagesOperations  # type: ignore
from ._virtual_machine_run_commands_operations import VirtualMachineRunCommandsOperations  # type: ignore
from ._usage_operations import UsageOperations  # type: ignore
from ._virtual_machine_scale_sets_operations import VirtualMachineScaleSetsOperations  # type: ignore
from ._virtual_machines_operations import VirtualMachinesOperations  # type: ignore
from ._virtual_machine_sizes_operations import VirtualMachineSizesOperations  # type: ignore
from ._proximity_placement_groups_operations import ProximityPlacementGroupsOperations  # type: ignore
from ._restore_point_collections_operations import RestorePointCollectionsOperations  # type: ignore
from ._ssh_public_keys_operations import SshPublicKeysOperations  # type: ignore
from ._capacity_reservations_operations import CapacityReservationsOperations  # type: ignore
from ._dedicated_hosts_operations import DedicatedHostsOperations  # type: ignore
from ._restore_points_operations import RestorePointsOperations  # type: ignore
from ._virtual_machine_scale_set_rolling_upgrades_operations import VirtualMachineScaleSetRollingUpgradesOperations  # type: ignore
from ._virtual_machine_scale_set_extensions_operations import VirtualMachineScaleSetExtensionsOperations  # type: ignore
from ._virtual_machine_scale_set_vms_operations import VirtualMachineScaleSetVMsOperations  # type: ignore
from ._virtual_machine_scale_set_vm_extensions_operations import VirtualMachineScaleSetVMExtensionsOperations  # type: ignore
from ._virtual_machine_scale_set_vm_run_commands_operations import VirtualMachineScaleSetVMRunCommandsOperations  # type: ignore
from ._virtual_machine_extensions_operations import VirtualMachineExtensionsOperations  # type: ignore

from ._patch import __all__ as _patch_all
from ._patch import *
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "Operations",
    "AvailabilitySetsOperations",
    "CapacityReservationGroupsOperations",
    "DedicatedHostGroupsOperations",
    "ImagesOperations",
    "VirtualMachineImagesEdgeZoneOperations",
    "VirtualMachineImagesOperations",
    "LogAnalyticsOperations",
    "VirtualMachineExtensionImagesOperations",
    "VirtualMachineRunCommandsOperations",
    "UsageOperations",
    "VirtualMachineScaleSetsOperations",
    "VirtualMachinesOperations",
    "VirtualMachineSizesOperations",
    "ProximityPlacementGroupsOperations",
    "RestorePointCollectionsOperations",
    "SshPublicKeysOperations",
    "CapacityReservationsOperations",
    "DedicatedHostsOperations",
    "RestorePointsOperations",
    "VirtualMachineScaleSetRollingUpgradesOperations",
    "VirtualMachineScaleSetExtensionsOperations",
    "VirtualMachineScaleSetVMsOperations",
    "VirtualMachineScaleSetVMExtensionsOperations",
    "VirtualMachineScaleSetVMRunCommandsOperations",
    "VirtualMachineExtensionsOperations",
]
__all__.extend([p for p in _patch_all if p not in __all__])  # pyright: ignore
_patch_sdk()
