# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
# pylint: disable=wrong-import-position

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ._patch import *  # pylint: disable=unused-wildcard-import

from ._operations import Operations  # type: ignore
from ._operations import VirtualMachineScaleSetsOperations  # type: ignore
from ._operations import RollingUpgradeStatusInfosOperations  # type: ignore
from ._operations import VirtualMachineScaleSetExtensionsOperations  # type: ignore
from ._operations import VirtualMachineScaleSetVMSOpsOperations  # type: ignore
from ._operations import VirtualMachineScaleSetVMSOperations  # type: ignore
from ._operations import VirtualMachineScaleSetVMExtensionsOperations  # type: ignore
from ._operations import VirtualMachinesOperations  # type: ignore
from ._operations import VirtualMachineExtensionsOperations  # type: ignore
from ._operations import VirtualMachineExtensionImageOpsOperations  # type: ignore
from ._operations import VirtualMachineExtensionImageTypeOpsOperations  # type: ignore
from ._operations import VirtualMachineExtensionImagesOperations  # type: ignore
from ._operations import AvailabilitySetsOperations  # type: ignore
from ._operations import ProximityPlacementGroupsOperations  # type: ignore
from ._operations import DedicatedHostGroupsOperations  # type: ignore
from ._operations import DedicatedHostsOperations  # type: ignore
from ._operations import SshPublicKeyResourcesOperations  # type: ignore
from ._operations import ImagesOperations  # type: ignore
from ._operations import RestorePointCollectionsOperations  # type: ignore
from ._operations import RestorePointsOperations  # type: ignore
from ._operations import CapacityReservationGroupsOperations  # type: ignore
from ._operations import CapacityReservationsOperations  # type: ignore
from ._operations import VirtualMachineRunCommandOpsOperations  # type: ignore
from ._operations import VirtualMachineRunCommandsOperations  # type: ignore
from ._operations import VirtualMachineScaleSetVMRunCommandOpsOperations  # type: ignore
from ._operations import VirtualMachineScaleSetVMRunCommandsOperations  # type: ignore
from ._operations import UsageOperationsOperations  # type: ignore
from ._operations import VirtualMachineSizesOperationsOperations  # type: ignore
from ._operations import VirtualMachineScaleSetsOperationsOperations  # type: ignore
from ._operations import VirtualMachinesOperationsOperations  # type: ignore
from ._operations import VirtualMachineImagesEdgeZoneOperationsOperations  # type: ignore
from ._operations import VirtualMachineImagesOperationsOperations  # type: ignore
from ._operations import LogAnalyticsOperationsOperations  # type: ignore
from ._operations import VirtualMachineRunCommandsOperationsOperations  # type: ignore

from ._patch import __all__ as _patch_all
from ._patch import *
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "Operations",
    "VirtualMachineScaleSetsOperations",
    "RollingUpgradeStatusInfosOperations",
    "VirtualMachineScaleSetExtensionsOperations",
    "VirtualMachineScaleSetVMSOpsOperations",
    "VirtualMachineScaleSetVMSOperations",
    "VirtualMachineScaleSetVMExtensionsOperations",
    "VirtualMachinesOperations",
    "VirtualMachineExtensionsOperations",
    "VirtualMachineExtensionImageOpsOperations",
    "VirtualMachineExtensionImageTypeOpsOperations",
    "VirtualMachineExtensionImagesOperations",
    "AvailabilitySetsOperations",
    "ProximityPlacementGroupsOperations",
    "DedicatedHostGroupsOperations",
    "DedicatedHostsOperations",
    "SshPublicKeyResourcesOperations",
    "ImagesOperations",
    "RestorePointCollectionsOperations",
    "RestorePointsOperations",
    "CapacityReservationGroupsOperations",
    "CapacityReservationsOperations",
    "VirtualMachineRunCommandOpsOperations",
    "VirtualMachineRunCommandsOperations",
    "VirtualMachineScaleSetVMRunCommandOpsOperations",
    "VirtualMachineScaleSetVMRunCommandsOperations",
    "UsageOperationsOperations",
    "VirtualMachineSizesOperationsOperations",
    "VirtualMachineScaleSetsOperationsOperations",
    "VirtualMachinesOperationsOperations",
    "VirtualMachineImagesEdgeZoneOperationsOperations",
    "VirtualMachineImagesOperationsOperations",
    "LogAnalyticsOperationsOperations",
    "VirtualMachineRunCommandsOperationsOperations",
]
__all__.extend([p for p in _patch_all if p not in __all__])  # pyright: ignore
_patch_sdk()
